name: EIP Manager
description: Request reviewers for EIP modifications
author: Pandapip1

inputs:
  token:
    description: GitHub token with repo permissions
    required: true
  pr_number:
    description: The PR Number
    required: false
    default: ''

runs:
  using: node16
  main: dist/index.js

branding:
  icon: settings
  color: gray-dark
