name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
        with:
          bun-version: 1.0.1

      - name: Cache node_modules
        id: cache-npm-packages
        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4.0.1
        env:
          cache-name: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}

      - name: Install Dependencies
        if: ${{ steps.cache-npm-packages.outputs.cache-hit != 'true' }}
        run: bun install

      - name: Build
        run: bun run build

      - name: Test
        run: bun run test
